// dod_kaust_b1.res - created with RESGen v2.0.3 DBG.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (89):
dod_charlie.wad
dod_chemille.wad
dod_escape.wad
dod_falaise.wad
dod_flash.wad
dod_jagd.wad
dod_kaust.wad
dod_kraftstoff.wad
dod_saints.wad
dod_sturm.wad
gfx/env/grnplsntbk.tga
gfx/env/grnplsntdn.tga
gfx/env/grnplsntft.tga
gfx/env/grnplsntlf.tga
gfx/env/grnplsntrt.tga
gfx/env/grnplsntup.tga
halflife.wad
hlbasics.wad
models/helmet_axis.mdl
models/helmet_us.mdl
models/mapmodels/arc_bush.mdl
models/mapmodels/arc_fern.mdl
models/mapmodels/arc_flower.mdl
models/mapmodels/barbed_wire.mdl
models/mapmodels/barrelcrash.mdl
models/mapmodels/bed_empty-wood.mdl
models/mapmodels/bookcase_green.mdl
models/mapmodels/books1.mdl
models/mapmodels/bord.mdl
models/mapmodels/bulb.mdl
models/mapmodels/by_barrel_brown.mdl
models/mapmodels/by_furniture_group-wreck.mdl
models/mapmodels/by_rubble_set.mdl
models/mapmodels/car021.mdl
models/mapmodels/couch_fabric-wreck.mdl
models/mapmodels/dn_dodge_wc54.mdl
models/mapmodels/dn_gas_lamp.mdl
models/mapmodels/dn_greyhound.mdl
models/mapmodels/dn_hotel_mailbox.mdl
models/mapmodels/dn_piano.mdl
models/mapmodels/dn_sandbags.mdl
models/mapmodels/dn_sdkfz_222.mdl
models/mapmodels/dn_sdkfz_251.mdl
models/mapmodels/dn_wolverine.mdl
models/mapmodels/dn_zundapp_ks600.mdl
models/mapmodels/dod_jagd_car.mdl
models/mapmodels/flo_bed.mdl
models/mapmodels/flo_coattree.mdl
models/mapmodels/flo_light.mdl
models/mapmodels/flo_pak37.mdl
models/mapmodels/furniture.mdl
models/mapmodels/furniture_group-hotel01.mdl
models/mapmodels/grandfather_clock1.mdl
models/mapmodels/hk_radio.mdl
models/mapmodels/lamp.mdl
models/mapmodels/m3_parkbench.mdl
models/mapmodels/mattress_wreck.mdl
models/mapmodels/merd_chim.mdl
models/mapmodels/pi_tree3.mdl
models/mapmodels/repunzel_bott.mdl
models/mapmodels/sandbags.mdl
models/mapmodels/shelves_wood.mdl
models/mapmodels/sign_shop.mdl
models/mapmodels/streetlight_saints.mdl
models/w_aflag.mdl
models/w_gflag.mdl
models/w_wflag.mdl
overviews/dod_kaust_b1.bmp
overviews/dod_kaust_b1.txt
sound/ambience/burning1.wav
sound/ambience/clocktick.wav
sound/ambience/dn_piano_angel_01.wav
sound/ambience/dn_piano_angel_02.wav
sound/ambience/dn_piano_ff7_01.wav
sound/ambience/dn_piano_ff7_02.wav
sound/ambience/dod_jagd_radio.wav
sound/ambience/dodambience4.wav
sound/ambience/germanwin.wav
sound/ambience/gerobjectivesecure.wav
sound/ambience/gerpointcaptured.wav
sound/ambience/truck-1ka.wav
sound/ambience/usobjectivesecure.wav
sound/ambience/uspointcaptured.wav
sound/ambience/uswin.wav
sprites/flames.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/mapsprites/caparea.spr
sprites/obj_tnt.spr
sprites/smoke_ia.spr
sprites/obj_icons/dod_kaust/icon_obj_custom1_allies.spr
sprites/obj_icons/dod_kaust/icon_obj_custom1_axis.spr
sprites/obj_icons/dod_kaust/icon_obj_custom2_allies.spr
sprites/obj_icons/dod_kaust/icon_obj_custom2_axis.spr
sprites/obj_icons/dod_kaust/icon_obj_custom3_allies.spr
sprites/obj_icons/dod_kaust/icon_obj_custom3_axis.spr